language: node_js
node_js:
- '0.10'
- '4'
env:
  matrix:
  - CC=clang CXX=clang++ npm_config_clang=1
  global:
    secure: X3nuBz69wMh6jSlREK3Fy2RDynmz+w1RDeeZjzn4k/2WzF6LU5V4zNhWsB1gk6qQ2ykUphMoqsOwFpcdx+2y/j0MFY+0wt87EpxuYXK+bFYhQ7cYQd/h4fmCy0K2G25mMidsDjuZM5X++irqu6S+sLB78dgyQF1h95j+xRxk9dXCQI47ciusMq+CFzwTPgx0r2kMbI3cn4qse4PSYrz4bSkCLbrc6r2qTHg+pXxE0jKltSUHAYgLDinhgKqgB2SfGK/SCjfwQlw5Twm8N5XVlTDdw5vGXEhsiY2L143rMZ/d2hehVAPNOe5yLyP7wOSy5LJoUpIBqc9YWarML2dTLxNUejWJahSTjJMq1z2MS9jS3CjfOKXZyZke2nShyHOiWBwLdzB9ZwCZiW79slDNoE6aM/sjmKrbUDrvajvGlEJ6ItA8Nxn5uwe0pHqgkUcJDcXTDsbewVLOyOReONGE8nJZn5KnsHlJzxaptaaGwPws3pJLX1weLiBzT1ebQpQETnldkGnMblWA5OBjcqPc+WYRJasnHZIECo1aFZRqs/q++jbwYNY05Ox8fJuvqMeTAf5PziNy3K618yaq1G2754evM01IkzVIpWTz8lDl7tXKHQoGF0amKiDpO95mhi63c6nTvJFyvehfOaMMPcDIKL54kM5BH9eUXB8qX9k0Ce0=
before_install:
- npm install -g npm@2
- echo -e "loglevel=http\n@mic:registry = https://npme.mic.com:4873/\n//npme.mic.com:4873/:_authToken
  = $NPME_TOKEN" > ~/.npmrc
cache:
  directories:
  - $HOME/.npm
notifications:
  slack:
    secure: GJ6Mt7EqDVgojSSVuZKhEioi7r072J8Uw5WvUfiUE+ANX37Iqb/1a6Z5F7JCjAz5SJQQRYdxwcU6r3uADIecfZaKPgMnzpfosk6y7sY1AYpFFWJ3JYCyFfwhvxmLBAxh08BY/mHYCAQ1es+d6yumaqGJYPEuzEsWLraHvcSoVSctKFd6FvKvaQuzqmB9JVuTR7yRyzRXPxapO+vfaB8zK7LUUDiLbUSv3M9E/U2ZokNyLS62ops22BrwR7kbZpsHupPibcHJ+g/nAE+zSF8b0u0y03mmyUgaA+eziGrCTJV9Y0h2UP0wjJW4RWOZ01T+5kDpmdxpijyEV18M8qcfY2/Tn/5q/9LMRTNzxSI/7PQuCCpGMpRtcdH7Pw8G4b/rHkmgLcxCHNnBOnjAVPCnXkW1OhcljdchgDRw3cqNVed5myALcBQct3P3q6+f7PSdGqIx5In6RJ+PZzF5AsteM5Pg87WXllls7JR1oYV9o/ewDveuzviXg5SwevryfoTqGPstGR0a8kWzOwRiaA7X/ksoT2aIohHyjBCtHAD/mJgcxac++5B8ACE6Kjt+1WxE37wXkjIe9EYN33LXD28HIBrH7EVrhceLQOWTZWCADechHLTyoqOq8IMOTy+3yWUJavwvv8FTxPL2ML019wS+JjqK30yWf7PHvqrs66RiNWI=
